wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    t:
      1:
      - 1
      4: 3.8.10
      5: 0.10.31
      8:
      - 5
lr:
  desc: null
  value: 0.0003
num_epochs:
  desc: null
  value: 1
num_filters:
  desc: null
  value: 16
