name: "Run isort"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Use isort
      uses: jamescurtin/isort-action@master
      with: 
          requirementsFiles: "requirements.txt requirements_tests.txt"
